basictemplates/basictemplates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from templateapp import views
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    url(r'^templateapp/', include('templateapp.urls')),
    url(r'^logout/$', views.user_logout, name = 'logout'),
    url(r'special/', views.special, name = 'special')
]

basictemplates/templateapp/urls.py
from django.conf.urls import url
from templateapp import views

app_name = 'templateapp'

urlpatterns = [
    url(r'^relative_url/$', views.relative_url, name = 'relative_url'),
    url(r'^others/$', views.others, name = 'others'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^user_login/$', views.user_login, name = 'user_login')
]

basictemplates/templateapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.PROTECT,)
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

basictemplates/templateapp/forms.py
from django import forms
from django.contrib.auth.models import User
from templateapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basictemplates/templateapp/views.py
from django.shortcuts import render
from templateapp.forms import UserForm, UserProfileInfo
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def index(response):
    return render(response, 'templateapp/index.html')

@login_required
def special(response):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(response):
    logout(response)
    return HttpResponseRedirect(reverse('index'))

def others(response):
    return render(response, 'templateapp/others.html')

def relative_url(response):
    return render(response, 'templateapp/relative_url.html')
def register(response):

    registered = False

    if response.method == "POST":

        user_form = UserForm(data = response.POST)
        profile_form = UserProfileInfo(data = response.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in response.FILES:
                profile.profile_pic = response.FILES['profile_pic']
            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfo()

    return render(response, 'templateapp/registration.html',
                            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(response):

    if response.method == 'POST':
        username = response.POST.get('username')
        password = response.POST.get('password')
        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(response, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and Password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")
    else:

        return render(response, 'templateapp/login.html', {})

basictemplates/templates/templateapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base.html</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li><a class="nav-brand" href = "{% url 'index' %}">BRAND</a></li>
          <li><a class="nav-link" href = "{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link" href = "{% url 'templateapp:others' %}">Other</a></li>

          {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="nav-link" href = "{% url 'templateapp:register' %}">Register</a></li>
            <li><a class="nav-link" href="{% url 'templateapp:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

basictemplates/templates/templateapp/index.html
{% extends "templateapp/base.html" %}
{% block body_block %}
  <h1>This is index.html</h1>
  <h2>Example of template inherintence from index</h2>
{% endblock %}

basictemplates/templates/templateapp/login.html
{% extends 'templateapp/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'templateapp:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit" name="" class="btn btn-primary" value="Submit">
  </form>
</div>
{% endblock %}

basictemplates/templates/templateapp/others.html
{% extends "templateapp/base.html" %}
{% block body_block %}
  <h1>This is others.html</h1>
  <h2>Example of template inherintence</h2>
{% endblock %}

basictemplates/templates/templateapp/registration.html
{% extends "templateapp/base.html" %}
{% load static %}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering</h1>
    {% else %}
      <h1>Register Here</h1>
      <h2>Fill out the form:</h2>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    {% endif %}
  </div>
{% endblock %}

basictemplates/templates/templateapp/relative_url.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>This is relative_url.html</h1>
    <a href="{% url 'templateapp:others' %}">Go To Others Page</a><br>
    <a href="{% url 'admin:index' %}">Go To Admin Page</a><br>
    <a href="{% url 'index' %}">Go To Home Page</a>
  </body>
</html>